#+TITLE: Abschlussprojekt Grundlagen Algorithmen  
#+SUBTITLE: Using Brute Force to sorting fictitious linear epitopes  
#+AUTHOR: Ricardo A. Orbegozo-Medina  
#+DATE: 23-02-2026  
#+LANGUAGE: en  
#+OPTIONS: toc:t num:t \n:t 

# % -------------- LATEX SETUP --------------
#+LATEX_COMPILER: xelatex
#+LATEX_CLASS: article
# % Margings: asymmetric for book-style layout
#+LATEX_HEADER: \usepackage[a4paper,inner=1.5in,outer=1.2in,top=0.8in,bottom=0.8in,includehead,headheight=15pt,twoside]{geometry}

# % Font setup: 
#+LATEX_HEADER: \usepackage{fontspec}                                  % set custom fonts
#+LATEX_HEADER: \setmainfont[Ligatures=TeX,Scale=1]{Liberation Sans}   % text font+size
#+LATEX_HEADER: \setmonofont[Ligatures=TeX,Scale=0.8]{Source Code Pro} % code font+size

# % --- Paragraph spacing: ---
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \setlength{\parskip}{0em}   % or 0.3em, 0.2em, etc.
#+LATEX_HEADER: \setlength{\parindent}{0pt}   % remoce paragraph indentation (sangria)
# remove indentation at the beggining of paragraphs
#+LATEX_HEADER: \usepackage{etoolbox}
#+LATEX_HEADER: \AtBeginEnvironment{document}{\justifying}
#+LATEX_HEADER: \usepackage{ragged2e}
#+LATEX_HEADER: \justifying

# % --- generate table of content (xelatex) ---
# % white page before toc
#+LATEX: \clearpage
#+LATEX: \thispagestyle{empty}
#+LATEX: \null
# #+LATEX: \newpage
# #+BEGIN_EXPORT latex
# \tableofcontents
# #+END_EXPORT
# #+LATEX: \clearpage
# % --- Color Support ---
#+LATEX_HEADER: \usepackage[x11names,svgnames,dvipsnames]{xcolor}
# --- 10 colores importantes ---
#+LATEX_HEADER: % Definir colores faltantes y fallback seguro
#+LATEX_HEADER: \definecolor{Gray30}{gray}{0.30} % define Gray30 como 30% negro
#+LATEX_HEADER: \definecolor{Gray50}{gray}{0.50} % (opcional) ejemplo adicional
#+LATEX_HEADER: \colorlet{basictextcolor}{Black!70}          % texto normal
#+LATEX_HEADER: \colorlet{keywordcolor}{DodgerBlue3!90}      % palabras clave
#+LATEX_HEADER: \colorlet{commentcolor}{Black!70}            % comentarios
#+LATEX_HEADER: \colorlet{stringcolor}{Goldenrod3!85}        % strings
#+LATEX_HEADER: \colorlet{numbercolor}{MediumPurple3!85}     % números
#+LATEX_HEADER: \colorlet{identifiercolor}{Black!85}         % variables
#+LATEX_HEADER: \colorlet{backgroundcolor}{GhostWhite}       % fondo
# #+LATEX_HEADER: \colorlet{backgroundcolor}{Gray10}       % fondo
#+LATEX_HEADER: \colorlet{rulecolor}{SlateGray3}             % bordes
#+LATEX_HEADER: \colorlet{outputcolor}{Gray30}               % salida de consola
#+LATEX_HEADER: \colorlet{promptcolor}{Gray50}               % símbolo >
# % --- code blocks format ---
# #+LATEX_HEADER: \usepackage{xcolor}
#+LATEX_HEADER: \usepackage{listings}
# #+LATEX_HEADER: \usepackage{listingsutf8} % deprecated in texlive 2025
#+LATEX_HEADER: \lstset{
#+LATEX_HEADER:   inputencoding=utf8,
#+LATEX_HEADER:   extendedchars=true,
#+LATEX_HEADER:   language=R,
# #+LATEX_HEADER:   basicstyle=\ttfamily\small\color{black},
#+LATEX_HEADER:   basicstyle=\ttfamily\color{black},
#+LATEX_HEADER:   keywordstyle=\color{keywordcolor},
#+LATEX_HEADER:   commentstyle=\color{commentcolor},
#+LATEX_HEADER:   stringstyle=\color{stringcolor},
#+LATEX_HEADER:   identifierstyle=\color{identifiercolor},
#+LATEX_HEADER:   numberstyle=\color{numbercolor},
#+LATEX_HEADER:   backgroundcolor=\color{backgroundcolor},
#+LATEX_HEADER:   morekeywords={mean,var,sd,data,print,summary,plot},
#+LATEX_HEADER:   showspaces=false,
#+LATEX_HEADER:   showstringspaces=false,
#+LATEX_HEADER:   breaklines=true,
#+LATEX_HEADER:   frame=none,
#+LATEX_HEADER:   columns=fullflexible
#+LATEX_HEADER: }
# % --- results verbatim blocks format ---
#+LATEX_HEADER: \usepackage{framed}
#+LATEX_HEADER: \definecolor{shadecolor}{named}{GhostWhite}
#+LATEX_HEADER: \let\oldverbatim\verbatim
#+LATEX_HEADER: \let\endoldverbatim\endverbatim
#+LATEX_HEADER: \renewenvironment{verbatim}
#+LATEX_HEADER:   {\begin{snugshade*}\oldverbatim}
#+LATEX_HEADER:   {\endoldverbatim\end{snugshade*}}


#+PROPERTY: header-args:R :session Rstat :results output :exports both


* Introduction

As a veterinarian dedicated to immunological research in animal models, one of the hot topics that I had work is the subunit-vaccine development, which requires the identification and prioritization of epitopes, peptide short sequences from proteins, potentially immunogenic. In this work I want to show how before in vitro or animal model experimentation, is necessary to organize lists of epitope candidates for subunit-vaccine according to different criteria, like peptide length, affinity for MHC molecules, physicochemistry properties or even more advanced models known as QSAR.

Despite sorting algorithms cannot predict immunogenicity, they represent a fundamental computational tool to sort biological data. The focus that I give to this project was to understand how the algorithm *insertion sort* could be implemented to sort a list of fictitious linear peptide epitopes according to their length, showing step by step how the algorithm works and its possible application to immunological data.

* Description of the algorithm

The idea of the *insertion sort* algorithm is to navigate a list of epitopes from left to right, taking one epitope and inserting it in the right position in the list. As a brute force sorting algorithm it will sequentially compare all the sequences.

Input: a list of linear epitope sequences \(e=(e_1,e_2,...,e_n)\).  
Output: an ascendingly sorted list of the epitopes in \(e\).

#+begin_export latex
\textbf{Algorithm Insertion Sort} $(e)$

\textbf{for} $i = 2$ \textbf{to} length$(e)$ \textbf{do}

\quad value to be inserted $\leftarrow e[i]$

\quad $j \leftarrow i - 1$

\quad \textbf{while} $j > 0$ \textbf{and} $e[j] >$ value to be inserted \textbf{do}

\qquad $e[j + 1] \leftarrow e[j]$

\qquad $j \leftarrow j - 1$

\quad \textbf{end while}

\quad $e[j + 1] \leftarrow$ value to be inserted

\textbf{end for}
#+end_export
#+LATEX: \clearpage
* Implementation in R

** Definition of fictitious epitopes using one letter code

#+BEGIN_SRC R :results output :exports both
aminoacids <- c(
  "A",  # Alanine
  "C",  # Cysteine
  "D",  # Aspartic acid
  "E",  # Glutamic acid
  "F",  # Phenylalanine
  "G",  # Glycine
  "H",  # Histidine
  "I",  # Isoleucine
  "K",  # Lysine
  "L",  # Leucine
  "M",  # Methionine
  "N",  # Asparagine
  "P",  # Proline
  "Q",  # Glutamine
  "R",  # Arginine
  "S",  # Serine
  "T",  # Threonine
  "V",  # Valine
  "W",  # Tryptophan
  "Y"   # Tyrosine
)
# generate epitope lengths randomnly between 4 to 7 residues
# epitope_lengths <- sample(4:7, 6, replace=TRUE) # samples will be replaced each time
epitope_lengths <- c(6,5,8,6,7,5) # samples will be replaced each time
# Generate random epitopes
epitopes <- sapply(epitope_lengths, function(len) {
  paste0(sample(aminoacids, len, replace = TRUE), collapse = "")
})
epitopes # show result sequences
nchar(epitopes) # show number of residues per sequence
#+END_SRC

#+RESULTS:
: [1] "HALGMC"   "EKVYW"    "VFTLFKPC" "MWAESW"   "QTWDMCN"  "YDFDW"
: [1] 6 5 8 6 7 5

#+LATEX: \clearpage
** Function: Insertion Sort by Length

#+BEGIN_SRC R :results output :exports both
insertion_sort_epitopes <- function(x) {
  steps = list() # keep rack of each (intermediate) step
  n = length(x) # how many aminoacids's
  steps[[1]] = x # save unsorted vector
  step_idx = 2  # start from second element
  for (i in 2:n) { # iterate vector
    key = x[i] # peptide to be sorted
    key_len = nchar(key) # peptide length
    j = i - 1 # start from backwards 
    while (j > 0 && nchar(x[j]) > key_len) {
      x[j + 1] = x[j] # move peptide to the right
      j = j - 1 # or keep moving to the left
    }
    x[j + 1] = key # drop the peptide in the right spot
    steps[[step_idx]] = x # save this step
    step_idx = step_idx + 1 # increment index by one
  }
  
  list(sorted = x, steps = steps) # return sorted epitope vector and steps
}

res = insertion_sort_epitopes(epitopes) # apply function to epitopes
res$sorted # show sorted epitopes
#+END_SRC

#+RESULTS:
: [1] "EKVYW"    "YDFDW"    "HALGMC"   "MWAESW"   "QTWDMCN"  "VFTLFKPC"

#+LATEX: \clearpage
** Results
Visualize intermediate states of this algorithm:

#+BEGIN_SRC R :results output :exports both
res$steps # show intermediate steps
#+END_SRC

#+RESULTS:
#+begin_example
[[1]]
[1] "HALGMC"   "EKVYW"    "VFTLFKPC" "MWAESW"   "QTWDMCN"  "YDFDW"   

[[2]]
[1] "EKVYW"    "HALGMC"   "VFTLFKPC" "MWAESW"   "QTWDMCN"  "YDFDW"   

[[3]]
[1] "EKVYW"    "HALGMC"   "VFTLFKPC" "MWAESW"   "QTWDMCN"  "YDFDW"   

[[4]]
[1] "EKVYW"    "HALGMC"   "MWAESW"   "VFTLFKPC" "QTWDMCN"  "YDFDW"   

[[5]]
[1] "EKVYW"    "HALGMC"   "MWAESW"   "QTWDMCN"  "VFTLFKPC" "YDFDW"   

[[6]]
[1] "EKVYW"    "YDFDW"    "HALGMC"   "MWAESW"   "QTWDMCN"  "VFTLFKPC"
#+end_example

** Interpretation

The initial epitopes vector has mixed lengths between 7 and 10 amino acids. After applying the *insertion sort* algorithm with length as sorting criterion, we obtain a list ordered from shortest to longest. As we discussed during the lecture, in the best scenario (already sorted epitope vector) the complexity is linear \(O(n)\) and in the worst and the regular scenario the complexity is quadratic \(O(n^2)\). It is not computational efficient but this is a necesary first step. The major justification here is that the linear epitopes used in vaccine development are very short peptide sequences of no more than 30 residues, which are an assumble cost. It should not be used bigger sizes because it generates steric hindrance which interfers with the stability of the molecule, and even shift the immunogenicity of it, as I know from experience... 

#+LATEX: \clearpage
* Further steps - sorting peptides by chemical properties implementing heapsort

Until now we sort peptides of different length, but what if the epitopes were the same length? In immunology, epitope prioritization rarely depends on a single feature such as peptide length; instead, it requires balancing several physicochemical properties that may conflict with one another.

For example, a peptide may be short (easy to synthesize) but highly polar (poor membrane accessibility), or aromatic (structurally stable) yet rich in heteroatoms (low permeability). This pattern of trade‑offs resembles QSAR (Quantitative Structure–Activity Relationship) approaches from chemoinformatics, which relate molecular structure to biological activity through quantitative descriptors.

Although QSAR originates in drug design, the idea of combining structural features to rank biological candidates is also relevant in bioinformatics. To explore this analogy in a simplified way, I implemented a set of *Simplified QSAR‑like descriptors* derived from the *SMILES representation* of amino acids, a compact string notation that encodes molecular structure. Below is the SMILES table used in this project:

#+begin_src R :results output
library(stringr)

aminoacids_smiles <- c(
  A="N[C@@H](C)C(=O)",               # Alanine
  C="N[C@@H](CS)C(=O)",              # Cysteine
  D="N[C@@H](CC(=O)O)C(=O)",         # Aspartic acid
  E="N[C@@H](CCC(=O)O)C(=O)",        # Glutamic acid
  F="N[C@@H](Cc1ccccc1)C(=O)",    # Phenylalanine (aromatic)
  G="NCC(=O)",                       # Glycine
  H="N[C@@H](Cc1ncc[nH]1)C(=O)",      # Histidine (aromatic imidazole)
  I="N[C@@H](C(C)CC)C(=O)",          # Isoleucine
  K="N[C@@H](CCCCN)C(=O)",           # Lysine
  L="N[C@@H](CC(C)C)C(=O)",          # Leucine
  M="N[C@@H](CCSC)C(=O)",            # Methionine
  N="N[C@@H](CC(=O)N)C(=O)",         # Asparagine
  P="N1CCC[C@H]1C(=O)",              # Proline
  Q="N[C@@H](CCC(=O)N)C(=O)",        # Glutamine
  R="N[C@@H](CCCNC(N)=N)C(=O)",      # Arginine
  S="N[C@@H](CO)C(=O)",              # Serine
  T="N[C@@H](C(O)C)C(=O)",           # Threonine
  V="N[C@@H](C(C)C)C(=O)",           # Valine
  W="N[C@@H](Cc1c[nH]c2ccccc12)C(=O)",  # Tryptophan (aromatic indole)
  Y="N[C@@H](Cc1ccc(O)cc1)C(=O)"  # Tyrosine (aromatic phenol)
)

#+end_src
#+LATEX: \clearpage
Here these SMILES strings will be use to define five simplifyed QSAR-like descriptors:

| Descriptor | Meaning        | How it is calculated             | Effect on score   |
|------------+----------------+----------------------------------+-------------------|
| Hy         | Hydrophobicity | Count of "C" atoms               | ↑ increases score |
| Ar         | Aromaticity    | Count of "C1=CC" patterns        | ↑ increases score |
| Po         | Polarity       | Count of "O" and "N"             | ↓ decreases score |
| He         | Heteroatoms    | Count of N, O, S                 | ↓ decreases score |
| Br         | Branching      | Count of parentheses "(" and ")" | ↑ increases score |
|            |                |                                  |                   |

These descriptors are not predictive models, but they mimic the logic of real QSAR features used in peptide design. Bellow is the calculation of the symplifyed QSAR descriptors, implemented in R code:

#+begin_src R :results output
calculate_descriptors <- function(peptide, smiles_table) {
  aminoacids = strsplit(peptide, "")[[1]] # split peptide into aminoacids
  smiles_vector = smiles_table[aminoacids] # get smile from an aminoacid
  smiles_all = paste(smiles_vector, collapse="")

  # ---- real Aromaticity ----
  Ar_atoms <- str_count(smiles_all, "[cn]")

  # ---- aprox Hidrofobicity ----
  C_atoms <- str_count(smiles_all, "C")

  # ---- Polarity ----
  O_atoms <- str_count(smiles_all, "O")
  N_atoms <- str_count(smiles_all, "N")
  Pol <- O_atoms + N_atoms

  # ---- Heteroatoms ----
  S_atoms <- str_count(smiles_all, "S")
  He <- O_atoms + N_atoms + S_atoms

  # ---- topologic Ramification ----
  Br <- str_count(smiles_all, "\\(")

  # return descriptors in a fix order
  list( Hy=C_atoms, Ar=Ar_atoms, Pol=Pol, He=He, Br=Br)
}
#+end_src
#+LATEX: \clearpage
** A score to rank sequences

To resolve contradictions between descriptors (e.g., a peptide may be short but highly hydrophobic), I defined a weighted score:

#+begin_example text
score = 2·Ar + 1·Hy - 1·Po - 1·He + 1·Br
#+end_example

This score favors hydrophobic and aromatic peptides, penalizes polarity and heteroatoms, and rewards branching.

Implemented in R this looks like this:
#+begin_src R :results output
calculate_score <- function(peptide) {
  descriptor <- calculate_descriptors(peptide, aminoacids_smiles)
  # Modelo lineal tipo QSAR
  2*descriptor$Ar      
  + 1.5*descriptor$Hy  
  + 1.2*descriptor$Pol 
  - 1.2*descriptor$He  
  - 0.5*descriptor$Br  
}

#+end_src

#+RESULTS:
#+LATEX: \clearpage
** Implementing a more efficient sorting algorithm: Heapsort

# Here we are going to use Heapsort, a classic sorting algorithm that is smarted and faster than insert sort, for a QSAR multi‑criteria score. This algorithm uses a structure called a heap. A heap is like a tree that is very organized: it is always complete and each node has two children. There are two types: a maxi‑heap, where each parent is bigger than its children, and a mini‑heap, where each parent is smaller. To sort from small to big, Heapsort uses a maxi‑heap.

# First, it builds the maxi‑heap so the biggest element is on top. Then it repeats this process: it takes the top element, puts it at the end of the sorted part, and fixes the heap again so it follows the rules.

# The algorithm has two steps: first it builds a maxi‑heap with all elements, so the biggest is on top. Then it repeats a process: it removes the top element (the biggest), puts it at the end of the list, and fixes the heap again.

# Unlike insertion sort, which takes about \(O(n^2)\), Heapsort works in \(O(n \log n)\). This makes it much faster and better for large lists.

In immunology, prioritization rarely relies on length alone; it requires balancing multiple, sometimes conflicting, physicochemical properties. here we are going to use heapsort, a classic sorting algorithm that is smarted and faster than insert sort, for a QSAR multi‑criteria score.

The heapsort algorithm uses a structure called a heap. A heap is like a tree that is very organized: it is always complete and each node has two children. There are two types: a maxi‑heap, where each parent is bigger than its children, and a mini‑heap, where each parent is smaller. To sort from small to big, heapsort uses a maxi‑heap.

Although QSAR originates in drug design, combining structural descriptors to rank candidates is relevant in bioinformatics. I implemented Simplified QSAR‑like descriptors derived from amino‑acid SMILES, a compact notation encoding molecular structure. Below is the SMILES table used in this project:

#+begin_src R :results output
heap_implementation <- function(arr, n, i) {
  largest = i # assume parent is largest
  l = 2*i # left child index
  r = 2*i + 1 # right child index

  if (l <= n && arr[l] > arr[largest]) largest = l # left child largest?
  if (r <= n && arr[r] > arr[largest]) largest = r # right larger?

  if (largest != i) { # case if child larger than parent
    tmp = arr[i]; arr[i] = arr[largest]
    arr[largest] = tmp # swap
    arr = heap_implementation(arr, n, largest) # fix subtree
  }
  arr # return updated array
}

heapsort <- function(arr) {
  n = length(arr) # number of aminoacids

  # build maxi heap
  for (i in floor(n/2):1) { # start from last parent
    arr = heap_implementation(arr, n, i)
  }

  # extract elements
  for (i in n:2) {
    tmp = arr[1]
    arr[1] = arr[i]
    arr[i] = tmp # move max to end
    arr[1:(i-1)] = heap_implementation(arr[1:(i-1)], i-1, 1) # resore heap
  }
  arr # sorted array
}
#+end_src
#+LATEX: \clearpage
** example implementing QSAR like descriptors and heapsort for epitope sorting/ranking

In this example we will start with epitopes of same length. like these:
#+begin_src R
# definition of six contrasting 9-mer peptides
peptides <- c(
  "LVIVVILVL", # Hydrophobic
  "FWYFYWFFY", # Aromatic
  "RKHHRKRRK", # Basic
  "EDDEEDDDE", # Acidic
  "STNQSTNQS", # Heteroatom rich
  "YHSWNYHFW" # Mixed aromatic polar
)
#+end_src

Below is the R implementation to calculate the QSAR scores:
#+begin_src R
scores <- sapply(epitopes, calculate_score)
cat("=> scores:\n")
print(scores)
#+end_src

Below the R implementation to sort epitopes by QSAR scores:
#+begin_src R
sorted_scores <- heapsort(scores)

cat("\n => Final result:\n")
order_idx <- order(scores) # index3es by ascending score
sorted_epitopes <- epitopes[order_idx]
cat("\n=> sorted epitopes ans scores:\n")
sorted_scores <- scores[order_idx]
print(sorted_scores)
#+end_src
#+LATEX: \clearpage

** *Interpretation:*

So far, the QSAR-like scoring system works using the Heapsort algorithm, which is smarter and faster than insertion sort. It also shows correctly what I wanted to demonstrate: that epitopes can be sorted according to their chemical properties using a score based on QSAR-like descriptors.

However, it has some limitations. The current SMILES represent isolated residues, not linked peptides. This means that I am not modeling real peptide bonds or considering the three-dimensional structure. What I did is only a proof of concept implementing heapsort and checimal properties together, but only summarizing molecular fragments, nothing more nothing less.
